### ISSUE TITLE
Command history

### ISSUE THREAD

**Issue by kyu08** [kyu08/fzf-make#79]
# UI
<img height="320" alt="image" src="https://github.com/kyu08/fzf-make/assets/49891479/5a71ca2a-eddf-4581-926e-e73d31c19622">

# Requirements
- Display histories
    - Read and parse history
    - Add UI in History pane
    - Test
        - Pass a history file path and check whether parse result is valid
- Update history
    - Update history when a target to be executed
        -  Append a target to head of histories
        - Remove duplicates
    - Test
        - At first update history, and then check content of history struct
        - Check some conversions of struct to file is valid
- Add `fzf-make --repeat` to execute the target last executed

## Data structure of history file
- `~/.config/fzf-make/history.toml`
- In the future, config file can be added. So this file is used only for history.

```toml
[[histories]]
path = "Users/john/projects/projectA"
executed-targets = ["test", "lint"]

[[histories]]
path = "Users/john/projects/projectB"
executed-targets = ["test", "lint"]

[[histories]]
path = "Users/john/projects/projectC"
executed-targets = ["test", "lint"]
```
